# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_initialize_logLikFn <- function(dv, contrasts, coef_constraints, data, predicted_criterion, cnames) {
    .Call('satf_rcpp_initialize_logLikFn', PACKAGE = 'satf', dv, contrasts, coef_constraints, data, predicted_criterion, cnames)
}

rcpp_deinitialize_logLikFn <- function() {
    .Call('satf_rcpp_deinitialize_logLikFn', PACKAGE = 'satf')
}

rcpp_compute_logLikFn <- function(coefs, by_row = FALSE) {
    .Call('satf_rcpp_compute_logLikFn', PACKAGE = 'satf', coefs, by_row)
}

rcpp_constrain_coefs <- function(coefs) {
    .Call('satf_rcpp_constrain_coefs', PACKAGE = 'satf', coefs)
}

rcpp_unconstrain_coefs <- function(coefs) {
    .Call('satf_rcpp_unconstrain_coefs', PACKAGE = 'satf', coefs)
}

rcpp_pnorm2d <- function(x_lower, y_lower, rho, order) {
    .Call('satf_rcpp_pnorm2d', PACKAGE = 'satf', x_lower, y_lower, rho, order)
}

rcpp_correlate <- function(trial_id, noise, rho_vec) {
    .Call('satf_rcpp_correlate', PACKAGE = 'satf', trial_id, noise, rho_vec)
}

rcpp_initialize_logLikFn <- function(dv, contrasts, coef_constraints, data, predicted_criterion, cnames) {
    .Call('satf_rcpp_initialize_logLikFn', PACKAGE = 'satf', dv, contrasts, coef_constraints, data, predicted_criterion, cnames)
}

rcpp_deinitialize_logLikFn <- function() {
    .Call('satf_rcpp_deinitialize_logLikFn', PACKAGE = 'satf')
}

rcpp_compute_logLikFn <- function(coefs, by_row = FALSE) {
    .Call('satf_rcpp_compute_logLikFn', PACKAGE = 'satf', coefs, by_row)
}

rcpp_constrain_coefs <- function(coefs) {
    .Call('satf_rcpp_constrain_coefs', PACKAGE = 'satf', coefs)
}

rcpp_unconstrain_coefs <- function(coefs) {
    .Call('satf_rcpp_unconstrain_coefs', PACKAGE = 'satf', coefs)
}

rcpp_pnorm2d <- function(x_lower, y_lower, rho, order) {
    .Call('satf_rcpp_pnorm2d', PACKAGE = 'satf', x_lower, y_lower, rho, order)
}

rcpp_correlate <- function(trial_id, noise, rho_vec) {
    .Call('satf_rcpp_correlate', PACKAGE = 'satf', trial_id, noise, rho_vec)
}

