# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_initialize_logLikFn <- function(params) {
    .Call('satf_rcpp_initialize_logLikFn', PACKAGE = 'satf', params)
}

rcpp_deinitialize_logLikFn <- function() {
    .Call('satf_rcpp_deinitialize_logLikFn', PACKAGE = 'satf')
}

rcpp_compute_logLikFn <- function(coefs, fixed_coefs) {
    .Call('satf_rcpp_compute_logLikFn', PACKAGE = 'satf', coefs, fixed_coefs)
}

